export const BannerEvents = Object.freeze( {
	BANNER_READY: 'BANNER_READY',
	BANNER_NOT_SHOWN: 'BANNER_NOT_SHOWN',
	BANNER_CLOSED: 'BANNER_CLOSED',
	TRANSITION_FINISHED: 'BANNER_NOT_SHOWN',
	BANNER_DIMENSIONS: 'BANNER_DIMENSIONS'
} );

export default BannerEvents;
